language: d

os:
  - linux
  - osx

d:
  - dmd-nightly
  - dmd-beta
  - dmd
  - dmd-2.074.0
  - dmd-2.072.2
  - dmd-2.068.2
  - ldc-beta
  - ldc
  - ldc-1.2.0
  - ldc-0.17.2
  - gdc

matrix:
  allow_failures:
      - d: gdc

script:
  - dub test

sudo: false
